### ISSUE TITLE
Request to add SeaLLM-7B-v2 in your paper tables.

### ISSUE THREAD

**Issue by nxphi47** [deepseek-ai/DeepSeek-Math#1]
Congrats on the super impressive results on math reasoning, we have many to learn from you!

We released [SeaLLM-7B-v2 (chat)](https://huggingface.co/SeaLLMs/SeaLLM-7B-v2) few days ago. It achieves 
**78.2** on GSM8K and **27.5** MATH and **64.8** on MGSM-zh. 

While our model is not as good as yours, we kindly request your team to include our results in your tables in [paper](https://arxiv.org/abs/2402.03300), and [this github repo](https://github.com/deepseek-ai/DeepSeek-Math).

**Comment by ZhihongShao** [comment]
We have included the performance of SeaLLM-v2 :)
