### ISSUE TITLE
Path Issue when running evals

### ISSUE THREAD

**Issue by yapdianang** [deepseek-ai/DeepSeek-Math#5]
Hi there! While trying to reproduce the evals of `python submit_eval_jobs.py --n-gpus 8` on 8 GPU A-100s, I came across an issue dumped in the logs:

`Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
Traceback (most recent call last):
  File "/home/ubuntu/src/DeepSeek-Math/evaluation/infer/run_cot_eval.py", line 11, in <module>
    from eval.utils import generate_completions, load_hf_lm_and_tokenizer
ModuleNotFoundError: No module named 'eval'`

Was wondering if this is familiar. I similar setup with the conda envs and packages, and I'm running out of `<path_to_local_repo>/evaluation`.

Some questions:
1. Is there any missing files like `__init__.py`?
2. Is the `MKL_THREADING_LAYER=INTEL` a cause of concern?

Thank you!

**Comment by ZhihongShao** [comment]
Thanks for letting us know this evaluation issue. We have updated the code. Would you mind trying it and see if it works for you?

**Comment by yapdianang** [comment]
Thank you for the fix, it works. Reinstalling numpy solve the `MKL_THREADING_LAYER=INTEL` issue. Thanks!
